### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by aliguran** [CodeMonsterPHD/GaTector-A-Unified-Framework-for-Gaze-Object-Prediction#7]
Hello,

When I try to train a model with your own goo_real_data, I get this error. How can I fix it have you faced before? I just tried to train.

Start Train
Epoch 1/50:   0%|                                                              | 0/225 [00:07<?, ?it/s<class 'dict'>]
Traceback (most recent call last):
  File "main.py", line 172, in <module>
    epoch_step, epoch_step_val, gen, gen_val, end_epoch, train_mode, Cuda)
  File "/root/GaTector-A-Unified-Framework-for-Gaze-Object-Prediction/lib/utils/utils_fit.py", line 47, in fit_one_epoch
    outputs = model_train(images, head, faces,train_mode)
  File "/opt/conda/envs/Gatector/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/Gatector/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.gather(outputs, self.output_device)
  File "/opt/conda/envs/Gatector/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 181, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/opt/conda/envs/Gatector/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 78, in gather
    res = gather_map(outputs)
  File "/opt/conda/envs/Gatector/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 73, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/opt/conda/envs/Gatector/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 73, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: zip argument #1 must support iteration

Thanks

**Comment by aliguran** [comment]
I was able to start training with your goo_synth_data. There is no problem with it. The only problem is related to real data training.
